/*DISTINCT FAZ A CONSULTA RETORNAR APENAS RESULTADOS UNICOS, EVITANDO DADOS DUPLICADOS*/
SELECT DISTINCT coluna1 FROM tabela
/*BUSCANDO NOMES UNICOS NA TABELA PERSON.PERSON*/
SELECT DISTINCT firstname FROM person.person
/*BUSCANDO SOBRENOMES UNICOS NA TABELA PERSON.PERSON*/
SELECT DISTINCT lastname FROM person.person;